version: '2'
services:
  nginx:
     build: ./nginx
     links: 
        - webserver1
        - webserver2
     ports:
        - "3000:80"
     networks:
        - mynetwork
  webserver1:
     build: ./webserver
     environment:
        - BUSINESS_LAYER_IP=businesslayer
        - BUSINESS_LAYER_PORT=8012
     links: 
        - businesslayer 
     ports:
        - "3000"
     volumes:
        - holdwebdata:/saveddata
     networks:
        - mynetwork
  webserver2:
     build: ./webserver
     environment:
        - BUSINESS_LAYER_IP=businesslayer
        - BUSINESS_LAYER_PORT=8012
     links: 
        - businesslayer 
     ports:
        - "3000"
     volumes:
        - holdwebdata:/saveddata
     networks:
        - mynetwork
  businesslayer:
     build: ./microservices
     stdin_open: true 
     ports:
        - "8012"
     networks:
        - mynetwork
networks:
  mynetwork:
    driver: "bridge"
volumes:
  holdwebdata:
    driver: "local"
